[package]
name = "os"
version = "0.1.0"
edition = "2024"

[lib]
name = "os"
crate-type = ["staticlib"]
test = false
doctest = false
bench = false

[dependencies]
num_enum = { version = "0.7.6", default-features = false }
spin = { version = "0.10.0", default-features = false, features = [
  "mutex",
  "once",
  "spin_mutex",
] }
